<?php

namespace AppBundle\Repository;

/**
 * AsinChildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsinChildRepository extends \Doctrine\ORM\EntityRepository
{
}
